src/main/java/com/group/docorofile/configs/GlobalExceptionHandler.java
src/main/java/com/group/docorofile/controllers/v1/api/user/UserInfoAPIController.java
src/main/java/com/group/docorofile/entities/MemberEntity.java
src/main/java/com/group/docorofile/models/dto/CommentDTO.java
src/main/java/com/group/docorofile/models/users/CreateUserRequest.java
src/main/java/com/group/docorofile/models/users/UpdateProfileRequest.java
src/main/java/com/group/docorofile/services/EmailService.java
src/main/java/com/group/docorofile/services/factories/AdminFactory.java
src/main/java/com/group/docorofile/services/factories/MemberFactory.java
src/main/java/com/group/docorofile/services/factories/ModeratorFactory.java
src/main/java/com/group/docorofile/services/factories/iUserFactory.java
src/main/java/com/group/docorofile/services/iUserService.java
src/main/java/com/group/docorofile/services/impl/UserServiceImpl.java
src/main/java/com/group/docorofile/services/strategies/AdminUpdateStrategy.java
src/main/java/com/group/docorofile/services/strategies/MemberUpdateStrategy.java
src/main/java/com/group/docorofile/services/strategies/ModeratorUpdateStrategy.java
src/main/java/com/group/docorofile/services/strategies/iUserUpdateStrategy.java
src/main/resources/application.properties

This pull request includes significant changes to the user management system, including validation improvements, new exception handling, and the introduction of a factory pattern for user creation. The most important changes are listed below.
* Added validation annotations to `CreateUserRequest` and `UpdateProfileRequest` classes to ensure required fields are present and properly formatted. (`[[1]](diffhunk://#diff-359618763b887c804d4713d6e06d376fc001b8f7a001b7768f96c224f952a2efR3-R38)`, `[[2]](diffhunk://#diff-8b3294a28ad905bc33e504491481451ac5ed3dce0e2a7475fab83d174c9074b1R1-R16)`)
* Implemented a new exception handler for `MethodArgumentNotValidException` in `GlobalExceptionHandler` to handle validation errors and return a `BadRequestError`. …

feat(user): implement user factories and update strategies for users

---

src/main/java/com/group/docorofile/controllers/management/report/ManageReportController.java
src/main/java/com/group/docorofile/controllers/v1/api/report/ReportAPIController.java
src/main/java/com/group/docorofile/repositories/ReportRepository.java
src/main/java/com/group/docorofile/services/iReportService.java
src/main/java/com/group/docorofile/services/impl/ReportServiceImpl.java
src/main/resources/static/js/page_reports.js
src/main/resources/templates/report/reports.html

This pull request introduces new functionality to retrieve and display detailed report information for documents, along with enforcing role-based access controls on relevant endpoints. The most important changes include adding a new API endpoint for fetching report details, implementing pagination for report details in the frontend, and securing endpoints with role-based access annotations.
* **New API Endpoint for Report Details**:
- Added a new method `getDetailReportByDocumentId` to `ReportAPIController` for fetching paginated report details by document ID. This method is secured with `@PreAuthorize` to allow access only to users with `ROLE_ADMIN` or `ROLE_MODERATOR`. (`[src/main/java/com/group/docorofile/controllers/v1/api/report/ReportAPIController.javaR73-R83](diffhunk://#diff-b1935c …

add report details

---

src/main/java/com/group/docorofile/controllers/client/NotificationController.java
src/main/java/com/group/docorofile/controllers/v1/api/notification/NotificationAPIController.java
src/main/java/com/group/docorofile/entities/NotificationEntity.java
src/main/java/com/group/docorofile/models/dto/NotificationDTO.java
src/main/java/com/group/docorofile/request/CreateNotificationMultiRequest.java
src/main/java/com/group/docorofile/services/iNotificationService.java
src/main/java/com/group/docorofile/services/impl/NotificationServiceImpl.java
src/main/resources/static/js/page_all_notifications.js
src/main/resources/templates/notification/all_notifications.html

This pull request introduces significant enhancements to the notification system, including new features, API updates, and a user interface for managing notifications. The most important changes include the addition of a new `NotificationController` for rendering the notification management page, updates to the notification API, enhancements to the notification entity and DTO, and the implementation of a frontend interface for viewing notifications.
* Renamed `NotificationController` to `NotificationAPIController` and added new endpoints to support system notifications and batch notifications. Updated the authorization roles to include `ROLE_MEMBER` and refactored the `createNotification` method to use the `CreateNotificationRequest` object. …

fix bugs & fix entity & add view all

---

src/main/resources/static/js/dropdown_notifications.js
src/main/resources/static/js/page_all_notifications.js
src/main/resources/templates/fragments/shared/header.html
src/main/resources/templates/layout.html
src/main/resources/templates/notification/all_notifications.html

This pull request introduces a new notification system with dynamic updates, improved UI, and modular page layouts. The changes include adding JavaScript functionality for loading and managing notifications, updating HTML templates for better integration and layout consistency, and enhancing user interaction with notifications.
* Added `updateNotificationBadge` and `loadDropdownNotifications` functions in `dropdown_notifications.js` to dynamically fetch and display notifications, update the badge count, and mark notifications as read.
* Modified `page_all_notifications.js` to hide the "Load More" button when there are no notifications on the first page.
* Updated `header.html` to integrate the dynamic notification badge and dropdown list, replacing static content with dynamically loaded …

feature(notification): Update notifications ui with layout

---

src/main/java/com/group/docorofile/controllers/v1/api/payment/PaymentAPIController.java
src/main/java/com/group/docorofile/controllers/v1/api/user/UserInfoAPIController.java
src/main/java/com/group/docorofile/entities/UserEntity.java
src/main/java/com/group/docorofile/models/dto/PaymentTableDTO.java
src/main/java/com/group/docorofile/models/users/UpdateUserRequest.java
src/main/java/com/group/docorofile/repositories/PaymentRepository.java
src/main/java/com/group/docorofile/services/PaymentService.java
src/main/java/com/group/docorofile/services/iUserService.java
src/main/java/com/group/docorofile/services/impl/UserServiceImpl.java
src/main/java/com/group/docorofile/services/strategies/MemberUpdateStrategy.java
src/main/java/com/group/docorofile/services/strategies/ModeratorUpdateStrategy.java
src/main/java/com/group/docorofile/services/strategies/iUserUpdateStrategy.java
src/main/java/com/group/docorofile/utils/DatabaseSeeder.java
src/main/java/com/group/docorofile/utils/PaymentSeeder.java
src/main/resources/static/assets/js/app-user-view-account.js
src/main/resources/static/assets/js/app-user-view.js
src/main/resources/static/assets/js/modal-edit-user.js
src/main/resources/templates/fragments/users/user-detail.html

This pull request introduces several enhancements and new features to the payment and user management systems. Key changes include adding new APIs for user and payment operations, creating DTOs for data transfer, and updating service implementations to support these functionalities. Below is a categorized summary of the most important changes:
* Added a new API in `PaymentAPIController` to retrieve payments by user with pagination and sorting, using the new `PaymentTableDTO` for data transfer. (`[[1]](diffhunk://#diff-b6c447a8744959fae37794c2213a6989b1a5924c0790d8acb5c56e1d5a578a5aR85-R103)`, `[[2]](diffhunk://#diff-43b24f9e3279de607efa147a89de26b985dc6999bc234b6f4cb5615d20a632a4R1-R24)`)
* Introduced a method in `PaymentService` to fetch paginated payment data for a specific user, …

Enhance Payment and User Management Systems with New APIs, DTOs, and Service Updates

---

src/main/resources/templates/fragments/report/reportForm.html

Ông chỉ cần thêm fragment này vào cái detail doc của ông và sửa cái dòng cứng này bằng cách truyền id của 2 cái đó động là đc nha @Killig3110

feature(manageReport): Xử lý màn hình báo cáo

---

src/main/java/com/group/docorofile/controllers/admin/CourseManageController.java
src/main/java/com/group/docorofile/controllers/admin/UniversityManageController.java
src/main/java/com/group/docorofile/controllers/client/FollowCourseController.java
src/main/java/com/group/docorofile/controllers/v1/api/course/CourseAPIController.java
src/main/java/com/group/docorofile/controllers/v1/api/followCourse/FollowCourseAPIController.java
src/main/java/com/group/docorofile/controllers/v1/api/university/UniversityAPIController.java
src/main/java/com/group/docorofile/models/course/CourseCreatedResponseDTO.java
src/main/java/com/group/docorofile/models/course/CourseDTO.java
src/main/java/com/group/docorofile/models/university/UniversityDTO.java
src/main/java/com/group/docorofile/repositories/UniversityRepository.java
src/main/java/com/group/docorofile/services/iFollowCourseService.java
src/main/java/com/group/docorofile/services/iUniversityService.java
src/main/java/com/group/docorofile/services/impl/CourseServiceImpl.java
src/main/java/com/group/docorofile/services/impl/FollowCourseServiceImpl.java
src/main/java/com/group/docorofile/services/impl/UniversityServiceImpl.java
src/main/resources/static/js/page_courses.js
src/main/resources/static/js/page_member_courses.js
src/main/resources/static/js/page_universities.js
src/main/resources/templates/fragments/course/course_detail.html
src/main/resources/templates/fragments/course/courses.html
src/main/resources/templates/fragments/course/member/courses.html
src/main/resources/templates/fragments/university/universities.html
src/main/resources/templates/fragments/university/university_detail.html
src/main/resources/templates/fragments/university/university_form.html

feature(univ_course & followCourse): Add UI for 2 features

---

src/main/resources/templates/document/document_uploads.html

This pull request enhances the file upload functionality in the `document_uploads.html` template by introducing an improved user experience, including a success animation, optimized file handling, and better error handling. The most important changes are grouped below:
* Added a success animation using Lottie to indicate when file uploads are complete. This includes a new `<div>` for the animation and the integration of the Lottie library. 
* Modified the `handleFiles` function to handle file uploads asynchronously, allowing a single `fetch` call for all files instead of multiple calls. 
* Fixed an issue with file icon rendering by removing support for the `.doc` extension, leaving only `.docx` as supported. 
These changes collectively improve the performance, reliability, and user …

feat(document-upload): enhance file upload process with success animation and improved error handling

---

src/main/resources/templates/document/document_uploads.html

This pull request improves the file upload functionality in the `document_uploads.html` template by enhancing progress control, refining animations, and simplifying the progress simulation logic. The changes focus on making the upload process smoother and more user-friendly.
* Introduced `progressControllers` to manage upload progress for each file, allowing all progress bars to be stopped and set to 100% upon completion. 
* Updated the success animation to loop continuously and changed the animation file path to a local resource (`/assets/json/success.json`) for improved reliability.
* Replaced the old `simulateProgress` function with `simulateProgressUntilComplete`, which removes delay factors and ensures progress slows down near completion. This change also introduces a `finish` method …

feat(document-upload): improve file upload progress handling with completion control

---

src/main/java/com/group/docorofile/controllers/client/FollowCourseController.java
src/main/java/com/group/docorofile/controllers/v1/api/followCourse/FollowCourseAPIController.java
src/main/resources/static/js/page_member_courses.js
src/main/resources/templates/fragments/course/member/courses.html
src/main/resources/templates/fragments/course/member/follow_courses.html

feature(followCourse): render documents list by courseId

---

src/main/resources/static/assets/js/app-user-view-account.js
src/main/resources/templates/chat/chat_room.html
src/main/resources/templates/layout.html

This pull request introduces changes to improve the user interface and navigation of the application, along with minor adjustments to the JavaScript and HTML templates. The key updates include modifications to the navigation menu, adjustments to the layout of the chat room, and updates to the handling of status badges in the JavaScript file.
* Added a new menu item for "Course followed" in the navigation menu (`src/main/resources/templates/layout.html`).
* Updated links for "Manage documents," "Manage university," and "Manage course" to point to their respective pages (`src/main/resources/templates/layout.html`).
* Adjusted the visibility and behavior of menu items based on user roles, including updates to the "Manage reports" link and visibility of "Course followed" …

feat(layout): add 'Course followed' menu item and update report management links for admin users

---

src/main/java/com/group/docorofile/controllers/v1/api/followCourse/FollowCourseAPIController.java

feature(followCourse): add check document when render document list
.exclude draft and deleted documents from course document list

feature(followCourse): add check document when render document list

---

Dockerfile
docker-compose.yml
src/main/java/com/group/docorofile/controllers/client/FileController.java
src/main/resources/templates/document/success_form.html
src/main/resources/templates/layout.html

This pull request introduces several updates to improve code maintainability, user experience, and debugging. Key changes include externalizing the document upload directory path, refining UI text and links, and adding debugging logs to the template scripts.
* [`FileController.java`](diffhunk://#diff-bc2def7cf59ce88c72fbd6783b8a6857fd683595362aa4e5a7375c891a2bcbcaR3): Externalized the document upload directory path by introducing a `@Value` annotation to inject the `document.upload.dir` property, replacing the hardcoded path. This enhances flexibility and maintainability. [[1]](diffhunk://#diff-bc2def7cf59ce88c72fbd6783b8a6857fd683595362aa4e5a7375c891a2bcbcaR3) [[2]](diffhunk://#diff-bc2def7cf59ce88c72fbd6783b8a6857fd683595362aa4e5a7375c891a2bcbcaR17-R24)
* …

feat(file-controller): refactor file path handling to use configurable upload director

---

src/main/java/com/group/docorofile/controllers/v1/api/document/DocumentAPIController.java
src/main/java/com/group/docorofile/security/JwtAuthenticationFilter.java
src/main/java/com/group/docorofile/security/SecurityConfig.java
src/main/java/com/group/docorofile/services/impl/DocumentServiceImpl.java
src/main/resources/templates/document/document_detail.html
src/main/resources/templates/document/document_uploads.html
src/main/resources/templates/document/metadata-form.html
src/main/resources/templates/document/success_form.html
src/main/resources/templates/layout.html

This pull request introduces several changes across the codebase, focusing on enhancing user experience, improving security, and refining functionality. Key updates include better handling of unauthenticated users, expanded API endpoint configurations, and improved navigation with return-to functionality.
* Updated `JwtAuthenticationFilter` to include additional API endpoints for documents and reactions in the list of permitted URLs. (`src/main/java/com/group/docorofile/security/JwtAuthenticationFilter.java`, [src/main/java/com/group/docorofile/security/JwtAuthenticationFilter.javaL84-R94](diffhunk://#diff-a781fc2079899bc520c70a7c6287a1395e1eb3103d5b92a351cc1571a45ced09L84-R94))
* Expanded public access in `SecurityConfig` to include new document-related API endpoints, ensuring proper …

feat(report): add user authentication check before reporting and enhance navigation with returnTo parameter

---

src/main/java/com/group/docorofile/models/mappers/DocumentMapper.java
src/main/java/com/group/docorofile/services/impl/CommentServiceImpl.java
src/main/resources/templates/document/manage_document.html

This pull request introduces changes to improve the handling of comments in the backend and enhances the responsiveness of the document management UI. Key updates include filtering root comments in DTO mappings, refactoring the comment tree-building logic, and improving the HTML structure for better table responsiveness.
* **Filter root comments in DTO mappings**: Updated `toUserDTO` and `toAdminDTO` methods in `DocumentMapper` to include only root comments (comments without a parent) when mapping comments to DTOs. (`src/main/java/com/group/docorofile/models/mappers/DocumentMapper.java`) [[1]](diffhunk://#diff-83083fbdd5c3bfdf959de6243d65703a1a043c10bc8140f2a84561f38287e0f1L38-R43) [[2]](diffhunk://#diff-83083fbdd5c3bfdf959de6243d65703a1a043c10bc8140f2a84561f38287e0f1L75-R85)
* **Refactor …

feat(comments): optimize comment retrieval and structure for better performance and clarity

---

src/main/java/com/group/docorofile/services/impl/MessageServiceImpl.java
src/main/resources/static/js/app-chat.js
src/main/resources/templates/chat/chat_room.html

This pull request introduces several changes to improve the user experience and functionality of the chat application, including updates to message display, localization, and conditional rendering for group chats. Below is a summary of the most important changes:
* Updated the sender information in the backend to display the sender's full name instead of their email address (`MessageServiceImpl.java`).
* Modified the frontend to display the sender's full name above each message in the chat history (`app-chat.js`).
* Changed the "No Chats Found" message in the chat sidebar to a localized Vietnamese message (`app-chat.js`).
* Updated the "Send" button text to its Vietnamese equivalent, "Gửi," in the chat room template (`chat_room.html`).
* Added logic to conditionally display a "no group …

feature(chat): fix ui for chat

---

src/main/java/com/group/docorofile/configs/VNPAYConfig.java
src/main/java/com/group/docorofile/controllers/client/PaymentController.java
src/main/java/com/group/docorofile/services/PaymentService.java
src/main/resources/templates/fragments/payment/error.html
src/main/resources/templates/fragments/payment/payment_status.html

feature(payment): fix UI for payment callback and payment error

---

src/main/java/com/group/docorofile/controllers/client/FollowCourseController.java
src/main/java/com/group/docorofile/controllers/v1/api/followCourse/FollowCourseAPIController.java
src/main/java/com/group/docorofile/repositories/FollowCourseRepository.java
src/main/java/com/group/docorofile/services/iCourseService.java
src/main/java/com/group/docorofile/services/iFollowCourseService.java
src/main/java/com/group/docorofile/services/impl/CourseServiceImpl.java
src/main/java/com/group/docorofile/services/impl/FollowCourseServiceImpl.java
src/main/resources/static/js/page_member_courses.js
src/main/resources/templates/fragments/course/member/courses.html
src/main/resources/templates/fragments/course/member/follow_courses.html

feature(followCourse): fix UI for followCourse

---

src/main/java/com/group/docorofile/services/factories/MemberFactory.java
src/main/java/com/group/docorofile/services/factories/ModeratorFactory.java
src/main/resources/static/assets/js/app-user-list.js
src/main/resources/templates/fragments/shared/header.html
src/main/resources/templates/layout.html

This pull request introduces several updates to improve user experience, enhance functionality, and address localization. The key changes include adjustments to default values for user entity creation, updates to user interface elements, and localization improvements for Vietnamese users.
* [`MemberFactory.java`](diffhunk://#diff-2e26045e7a823141d1ae40f69715dcb55f50e653e61ba73547b06ee283ad93b0L56-R57): Modified `isChat` and `isComment` fields to use default values (`true` and `false`, respectively) when null is provided in the request.
* [`ModeratorFactory.java`](diffhunk://#diff-e63c87e9d35b2ead61ddd17502a4e9ab2f1d222e90a2fad83610cff190bd1696L28-R28): Updated `isReportManage` to default to `true` if the value is null in the request.
* …

feat(localization): update notification titles and button text 

---

src/main/java/com/group/docorofile/repositories/DocumentRepository.java
src/main/java/com/group/docorofile/services/impl/DocumentServiceImpl.java

This pull request introduces a new search feature for document suggestions and refactors the related service logic for improved clarity and functionality. The most important changes include adding a new query method in the `DocumentRepository`, refactoring the `getSearchSuggestions` method in `DocumentServiceImpl`, and cleaning up unused logic.
* **`DocumentRepository`**: Added a new query method `searchSuggestions` to retrieve documents based on a keyword, excluding documents with statuses `DELETED` or `DRAFT`, and ordering the results by the upload date in descending order. This method uses a custom JPQL query with parameters. (`src/main/java/com/group/docorofile/repositories/DocumentRepository.java`, [src/main/java/com/group/docorofile/repositories/DocumentRepository.javaR42-R45](diffhu …

feat(document-repository): add search suggestions method to filter documents by title and status
